name: juce_ipc
description: Implementation of inter-process communication classes from JUCE
version: 0.0.1
homepage: https://github.com/Barabas5532/flutter_juce_ipc

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  freezed_annotation: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  freezed: ^2.0.0
  build_runner: ^2.0.0
  test: ^1.0.0
  dcli_core: ^1.36.0
  path: ^1.8.3
  stdlibc: ^0.1.1
